name: Update README.md

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        run: ./README.md
